[run]
tEnd        = 0.7
nStepmax    = 100000
output_frequency    = 20

initial_conditions = gadget,uniform

[gadget]
inputFile = /data/anatole/cloud/ICs/cloud_64.hdf5

[constant_metallicity]
metallicity     = 0.0139e-1
metals          = H,He,C,O
metal_mass      = 1.008,4.0026,12.0107,15.9994

ions        = xH_I,xH_II,xH2,xHe_I,xHe_II,xHe_III,xC_I,xC_II,xC_III,xC_IV,xC_V,xC_VI,xC_VII,xO_I,xO_II,xO_III,xO_IV,xO_V,xO_VI,xO_VII,xO_VIII,xO_IX
ion_fracs   = 1,0,0,1,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0

cie_initialization = true

[InitialConditions_uniform]
fields  = e_rad_0,fx_rad_0,fy_rad_0,fz_rad_0,e_rad_1,fx_rad_1,fy_rad_1,fz_rad_1,e_rad_2,fx_rad_2,fy_rad_2,fz_rad_2,e_rad_3,fx_rad_3,fy_rad_3,fz_rad_3,e_rad_4,fx_rad_4,fy_rad_4,fz_rad_4,e_rad_5,fx_rad_5,fy_rad_5,fz_rad_5
values = 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

[passive_scalars]
n_passive_scalars = 27
passive_scalars_init    = constant_metallicity,set_refinement
passive_scalars_names   = nH,nHe,nC,nO,xH_I,xH_II,xH2,xHe_I,xHe_II,xHe_III,xC_I,xC_II,xC_III,xC_IV,xC_V,xC_VI,xC_VII,xO_I,xO_II,xO_III,xO_IV,xO_V,xO_VI,xO_VII,xO_VIII,xO_IX,refinement

refinement_scalar_name            = refinement
set_refinement_density_threshold = 1e3 proton_mass/cm**3

refine_passive_scalar_threshold = 0.2

; [particles]
; update_density              = ParticleUpdate_CIC_density
; update_position             = ParticleUpdate_CIC_move
; density_projected_arrays    = particles

; source_term = ParticleUpdate_star_formation,ParticleUpdate_feedback,ParticleUpdate_radiative_feedback_BPASS

; [star_formation]
; density_threshold     = 1e7 proton_mass/cm**3 
; epsilon_star          = 0.5

[star_feedback]
bpass_data_path   = /data/anatole/BPASS/
temp_metallicity  = 0.0139e-1
star_birth_time_min = 0 Myr

[dt]
;,Compute_dt_particle,Compute_dt_rad,Compute_dt_gravity
dt_kernel       = Compute_dt_rad,Compute_dt_hydro
hydro_cfl        = 0.5
wait_for_radiation = true

; [gravity]
; solver = GravitySolver_cg
; CG_eps = 1e-1
; 4_Pi_G = 5.65298452e-11

[amr]
level_min = 4
level_max = 9

bx = 4
by = 4
bz = 4

nbOctsPerGroup = 1024

;markers_kernel = RefineCondition_jeans,RefineCondition_passive_scalar

jeans_refine                  = 2
jeans_coarsen                = 3

cycle_frequency             = 10000000

load_balancing_frequency        = 10000000

[mesh]
ndim = 3

xmin = 0.0
xmax = 0.04

ymin = 0.0
ymax = 0.04

zmin = 0.0
zmax = 0.04

boundary_type_xmin = absorbing
boundary_type_xmax = absorbing

boundary_type_ymin = absorbing
boundary_type_ymax = absorbing

boundary_type_zmin = absorbing
boundary_type_zmax = absorbing

[hydro]
dual_energy     = true 
dual_energy_eta = 0.5

gamma0      = 1.666
riemann     = hllc
update      = HydroUpdate_euler_27_passive_scalars


[rad]
update  = RadUpdate_euler_M1
c_rad   = 0.01 speedofLight

absorbing_bc = true

n_groups            = 6
photon_groups_lower = 5.6,11.2,13.6,15.2,24.59,54.42
photon_groups_upper = 11.2,13.6,15.2,24.59,54.42,500.0

[source_terms]
updates = SourceUpdate_Turbulent_Forcing
;updates = CoolingUpdate_PRISM_hydro

[turbulent_forcing]
T_driv = 0.7
chi = 100
turbulence_rms = 1
random_seed = 42

[cooling]
data_path   = /home/storckanatole/repos/Dyablo/core/src/source_terms/PRISM/gizmo_rtz/data
ions        = H_I,H_II,H2,He_I,He_II,He_III,C_I,C_II,C_III,C_IV,C_V,C_VI,C_VII,O_I,O_II,O_III,O_IV,O_V,O_VI,O_VII,O_VIII,O_IX

[movie]
enabled             = true
image_resolution    = 256
width               = 0.04 kpc
time_cadence        = 0.005 Myr
output_variables    = rho,xH2,e_rad_1,e_rad_2,xO_II,xO_III
projection_axis     = z,y
trigger_on_output   = false
output_first_iter    = false

[output]
outputDir                   = /data/anatole/cloud/sim/
outputPrefix                 = cloud

write_variables             = rho,rho_vx,rho_vy,rho_vz,e_tot,e_int,e_rad_0,e_rad_1,e_rad_2,e_rad_3,e_rad_4,e_rad_5,nH,nHe,nC,nO,xH_I,xH_II,xH2,xHe_I,xHe_II,xHe_III,xC_I,xC_II,xC_III,xC_IV,xC_V,xC_VI,xC_VII,xO_I,xO_II,xO_III,xO_IV,xO_V,xO_VI,xO_VII,xO_VIII,xO_IX,PRISM_iter,refinement
; write_particle_variables    = particles/vx,particles/vy,particles/vz,particles/mass,particles/birth_time

[units]
length  = 1 kpc
time    = 1 Myr
mass    = 1 solar_mass
