[run]
tEnd        = 50
nStepmax    = 1000000
output_frequency    = 1000
checkpoint_frequency = 2000

initial_conditions = gadget,uniform

[gadget]
inputFile = /data100/astorck/G8/ICs/G8_supersample_256.hdf5

[constant_metallicity]
Z_over_Zsun     = 0.1
metals          = H,He,C,N,O,Ne,Mg,Si,S,Fe
metal_mass      = 1.008,4.0026,12.0107,14.0067,15.9994,20.1797,24.305,28.0855,32.065,55.854

ions        = xH_I,xH_II,xH2,xHe_I,xHe_II,xHe_III,xC_I,xC_II,xC_III,xC_IV,xC_V,xC_VI,xC_VII,xN_I,xN_II,xN_III,xN_IV,xN_V,xN_VI,xN_VII,xN_VIII,xO_I,xO_II,xO_III,xO_IV,xO_V,xO_VI,xO_VII,xO_VIII,xO_IX,xNe_I,xNe_II,xNe_III,xNe_IV,xNe_V,xNe_VI,xNe_VII,xNe_VIII,xNe_IX,xNe_X,xNe_XI,xMg_I,xMg_II,xMg_III,xMg_IV,xMg_V,xMg_VI,xMg_VII,xMg_VIII,xMg_IX,xMg_X,xMg_XI,xMg_XII,xMg_XIII,xSi_I,xSi_II,xSi_III,xSi_IV,xSi_V,xSi_VI,xSi_VII,xSi_VIII,xSi_IX,xSi_X,xSi_XI,xSi_XII,xSi_XIII,xSi_XIV,xSi_XV,xS_I,xS_II,xS_III,xS_IV,xS_V,xS_VI,xS_VII,xS_VIII,xS_IX,xS_X,xS_XI,xS_XII,xS_XIII,xS_XIV,xS_XV,xS_XVI,xS_XVII,xFe_I,xFe_II,xFe_III,xFe_IV,xFe_V,xFe_VI,xFe_VII,xFe_VIII,xFe_IX,xFe_X,xFe_XI,xFe_XII,xFe_XIII,xFe_XIV,xFe_XV,xFe_XVI,xFe_XVII,xFe_XVIII,xFe_XIX,xFe_XX,xFe_XXI,xFe_XXII,xFe_XXIII,xFe_XXIV,xFe_XXV,xFe_XXVI,xFe_XXVII
cie_initialization = true

[InitialConditions_uniform]
fields  = e_rad_0,fx_rad_0,fy_rad_0,fz_rad_0,e_rad_1,fx_rad_1,fy_rad_1,fz_rad_1,e_rad_2,fx_rad_2,fy_rad_2,fz_rad_2,e_rad_3,fx_rad_3,fy_rad_3,fz_rad_3,e_rad_4,fx_rad_4,fy_rad_4,fz_rad_4,e_rad_5,fx_rad_5,fy_rad_5,fz_rad_5
values = 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

[passive_scalars]
n_passive_scalars       = 124
passive_scalars_init    = constant_metallicity
passive_scalars_names   = nH,nHe,nC,nN,nO,nNe,nMg,nSi,nS,nFe,nCO,xH_I,xH_II,xH2,xHe_I,xHe_II,xHe_III,xC_I,xC_II,xC_III,xC_IV,xC_V,xC_VI,xC_VII,xN_I,xN_II,xN_III,xN_IV,xN_V,xN_VI,xN_VII,xN_VIII,xO_I,xO_II,xO_III,xO_IV,xO_V,xO_VI,xO_VII,xO_VIII,xO_IX,xNe_I,xNe_II,xNe_III,xNe_IV,xNe_V,xNe_VI,xNe_VII,xNe_VIII,xNe_IX,xNe_X,xNe_XI,xMg_I,xMg_II,xMg_III,xMg_IV,xMg_V,xMg_VI,xMg_VII,xMg_VIII,xMg_IX,xMg_X,xMg_XI,xMg_XII,xMg_XIII,xSi_I,xSi_II,xSi_III,xSi_IV,xSi_V,xSi_VI,xSi_VII,xSi_VIII,xSi_IX,xSi_X,xSi_XI,xSi_XII,xSi_XIII,xSi_XIV,xSi_XV,xS_I,xS_II,xS_III,xS_IV,xS_V,xS_VI,xS_VII,xS_VIII,xS_IX,xS_X,xS_XI,xS_XII,xS_XIII,xS_XIV,xS_XV,xS_XVI,xS_XVII,xFe_I,xFe_II,xFe_III,xFe_IV,xFe_V,xFe_VI,xFe_VII,xFe_VIII,xFe_IX,xFe_X,xFe_XI,xFe_XII,xFe_XIII,xFe_XIV,xFe_XV,xFe_XVI,xFe_XVII,xFe_XVIII,xFe_XIX,xFe_XX,xFe_XXI,xFe_XXII,xFe_XXIII,xFe_XXIV,xFe_XXV,xFe_XXVI,xFe_XXVII

[particles]
families                = dark_matter,stars
update_density          = ParticleUpdate_CIC_density
update_position         = ParticleUpdate_CIC_move

source_term = ParticleUpdate_star_formation,ParticleUpdate_feedback,ParticleUpdate_radiative_feedback_BPASS
; ParticleUpdate_star_formation_turbulent

[star_formation]
density_threshold     = 1e3 proton_mass/cm**3
epsilon_star          = 0.01

[star_feedback]
star_family       = stars
bpass_data_path   = /data100/astorck/BPASS/

[dt]
dt_kernel       = Compute_dt_particle_velocity,Compute_dt_hydro,Compute_dt_rad
hydro_cfl        = 0.8
particle_cfl     = 0.8
wait_for_radiation = false

[gravity]
solver = GravitySolver_cg
CG_eps = 1e-1
4_Pi_G = 5.65298452e-11

[amr]
level_min = 4
level_max = 9

bx = 8
by = 8
bz = 8

nbOctsPerGroup = 1024

markers_kernel              = RefineCondition_mass,RefineCondition_jeans

mass_type                   = gas
mass_refine                  = 8e3
mass_coarsen                = 1e3

jeans_refine                 = 4
jeans_coarsen               = 8

cycle_frequency             = 20
load_balancing_frequency    = 1000000

[mesh]
ndim = 3

xmin = 0.0
xmax = 18.75

ymin = 0.0
ymax = 18.75

zmin = 0.0
zmax = 18.75

boundary_type_xmin = periodic
boundary_type_xmax = periodic

boundary_type_ymin = periodic
boundary_type_ymax = periodic

boundary_type_zmin = periodic
boundary_type_zmax = periodic

[hydro]
dual_energy     = true
dual_energy_eta = 0.5

gamma0      = 1.666
riemann     = hllc
update      = HydroUpdate_euler_124_passive_scalars

[rad]
update  = RadUpdate_euler_M1
c_rad   = 0.01 speedofLight

absorbing_bc = true

n_groups            = 6
photon_groups_lower = 5.6,11.2,13.6,15.2,24.59,54.42
photon_groups_upper = 11.2,13.6,15.2,24.59,54.42,500.0

uvb_spectrum_file  = /home/astorck/UVB.out
uvb_injection_mode = floor
uvb_boost = 1e0
uvb_sub_ionizing_only = false
uvb_initial_fill   = false
uvb_redshift       = 0.0

[source_terms]
updates = SourceUpdate_UV_Background,CoolingUpdate_PRISM_GPU_hydro

[cooling]
max_substeps        = 100000
rt_smooth           = true
rad_residual_floor   = 1e-3
include_HM12_UVB    = false
UV_background_G0    = 0.0
data_path           = /home/astorck/repos/Dyablo/core/src/source_terms/PRISM/gizmo_rtz/data
ions       = H_I,H_II,H2,He_I,He_II,He_III,C_I,C_II,C_III,C_IV,C_V,C_VI,C_VII,N_I,N_II,N_III,N_IV,N_V,N_VI,N_VII,N_VIII,O_I,O_II,O_III,O_IV,O_V,O_VI,O_VII,O_VIII,O_IX,Ne_I,Ne_II,Ne_III,Ne_IV,Ne_V,Ne_VI,Ne_VII,Ne_VIII,Ne_IX,Ne_X,Ne_XI,Mg_I,Mg_II,Mg_III,Mg_IV,Mg_V,Mg_VI,Mg_VII,Mg_VIII,Mg_IX,Mg_X,Mg_XI,Mg_XII,Mg_XIII,Si_I,Si_II,Si_III,Si_IV,Si_V,Si_VI,Si_VII,Si_VIII,Si_IX,Si_X,Si_XI,Si_XII,Si_XIII,Si_XIV,Si_XV,S_I,S_II,S_III,S_IV,S_V,S_VI,S_VII,S_VIII,S_IX,S_X,S_XI,S_XII,S_XIII,S_XIV,S_XV,S_XVI,S_XVII,Fe_I,Fe_II,Fe_III,Fe_IV,Fe_V,Fe_VI,Fe_VII,Fe_VIII,Fe_IX,Fe_X,Fe_XI,Fe_XII,Fe_XIII,Fe_XIV,Fe_XV,Fe_XVI,Fe_XVII,Fe_XVIII,Fe_XIX,Fe_XX,Fe_XXI,Fe_XXII,Fe_XXIII,Fe_XXIV,Fe_XXV,Fe_XXVI,Fe_XXVII

[movie]
enabled             = true
image_resolution    = 512
width               = 4 kpc
time_cadence        = 0.05 Myr
output_variables    = rho,xH_I,xH2,xC_II,xC_IV,xO_II,xO_III,e_rad_0,e_rad_1,e_rad_2
projection_axis     = z,y
trigger_on_output   = false
output_first_iter    = false

[output]
outputDir                   = /data100/astorck/G8/sim/production/
outputPrefix                 = fullNetwork

write_variables             = rho,rho_vx,rho_vy,rho_vz,e_tot,e_int,e_rad_0,e_rad_1,e_rad_2,e_rad_3,e_rad_4,e_rad_5,nH,nHe,nC,nN,nO,nNe,nMg,nSi,nS,nFe,nCO,xH_I,xH_II,xH2,xHe_I,xHe_II,xHe_III,xC_I,xC_II,xC_III,xC_IV,xC_V,xC_VI,xC_VII,xN_I,xN_II,xN_III,xN_IV,xN_V,xN_VI,xN_VII,xN_VIII,xO_I,xO_II,xO_III,xO_IV,xO_V,xO_VI,xO_VII,xO_VIII,xO_IX,xNe_I,xNe_II,xNe_III,xNe_IV,xNe_V,xNe_VI,xNe_VII,xNe_VIII,xNe_IX,xNe_X,xNe_XI,xMg_I,xMg_II,xMg_III,xMg_IV,xMg_V,xMg_VI,xMg_VII,xMg_VIII,xMg_IX,xMg_X,xMg_XI,xMg_XII,xMg_XIII,xSi_I,xSi_II,xSi_III,xSi_IV,xSi_V,xSi_VI,xSi_VII,xSi_VIII,xSi_IX,xSi_X,xSi_XI,xSi_XII,xSi_XIII,xSi_XIV,xSi_XV,xS_I,xS_II,xS_III,xS_IV,xS_V,xS_VI,xS_VII,xS_VIII,xS_IX,xS_X,xS_XI,xS_XII,xS_XIII,xS_XIV,xS_XV,xS_XVI,xS_XVII,xFe_I,xFe_II,xFe_III,xFe_IV,xFe_V,xFe_VI,xFe_VII,xFe_VIII,xFe_IX,xFe_X,xFe_XI,xFe_XII,xFe_XIII,xFe_XIV,xFe_XV,xFe_XVI,xFe_XVII,xFe_XVIII,xFe_XIX,xFe_XX,xFe_XXI,xFe_XXII,xFe_XXIII,xFe_XXIV,xFe_XXV,xFe_XXVI,xFe_XXVII,PRISM_iter
write_particle_variables    = stars/vx,stars/vy,stars/vz,stars/birth_time,stars/birth_mass,stars/mass

[units]
length  = 1 kpc
time    = 1 Myr
mass    = 1 solar_mass
