[run]
tEnd        = 50
nStepmax    = 5
output_frequency    = 500
checkpoint_frequency = 2000

initial_conditions = gadget,uniform

[gadget]
inputFile = /data100/astorck/G8/ICs/G8_supersample_256.hdf5

[constant_metallicity]
Z_over_Zsun     = 0.1
metals          = H,He,C,O
metal_mass      = 1.008,4.0026,12.0107,15.9994

ions        = xH_I,xH_II,xH2,xHe_I,xHe_II,xHe_III,xC_I,xC_II,xC_III,xC_IV,xC_V,xC_VI,xC_VII,xO_I,xO_II,xO_III,xO_IV,xO_V,xO_VI,xO_VII,xO_VIII,xO_IX
cie_initialization = true

[InitialConditions_uniform]
fields  = e_rad_0,fx_rad_0,fy_rad_0,fz_rad_0,e_rad_1,fx_rad_1,fy_rad_1,fz_rad_1,e_rad_2,fx_rad_2,fy_rad_2,fz_rad_2,e_rad_3,fx_rad_3,fy_rad_3,fz_rad_3,e_rad_4,fx_rad_4,fy_rad_4,fz_rad_4,e_rad_5,fx_rad_5,fy_rad_5,fz_rad_5
values = 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

[passive_scalars]
n_passive_scalars       = 27
passive_scalars_init    = constant_metallicity
passive_scalars_names   = nH,nHe,nCO,nC,nO,xH_I,xH_II,xH2,xHe_I,xHe_II,xHe_III,xC_I,xC_II,xC_III,xC_IV,xC_V,xC_VI,xC_VII,xO_I,xO_II,xO_III,xO_IV,xO_V,xO_VI,xO_VII,xO_VIII,xO_IX

[particles]
families                = dark_matter,stars
update_density          = ParticleUpdate_CIC_density
update_position         = ParticleUpdate_CIC_move

source_term = ParticleUpdate_star_formation,ParticleUpdate_feedback,ParticleUpdate_radiative_feedback_BPASS
; ParticleUpdate_star_formation_turbulent

[star_formation]
density_threshold     = 1e3 proton_mass/cm**3
epsilon_star          = 0.6
; particle_mass = 1830 solar_mass

[star_feedback]
star_family       = stars
bpass_data_path   = /data100/astorck/BPASS/

[dt]
dt_kernel       = Compute_dt_particle_velocity,Compute_dt_hydro,Compute_dt_rad
hydro_cfl        = 0.7
particle_cfl     = 0.7
wait_for_radiation = false

[gravity]
solver = GravitySolver_cg
CG_eps = 1e-1
4_Pi_G = 5.65298452e-11

[amr]
level_min = 4
level_max = 10

bx = 8
by = 8
bz = 8

nbOctsPerGroup = 1024

markers_kernel              = RefineCondition_mass,RefineCondition_jeans

mass_type                   = gas
mass_refine                  = 8e3
mass_coarsen                = 1e3

jeans_refine                 = 4
jeans_coarsen               = 8

cycle_frequency             = 100
load_balancing_frequency    = 1000000

[mesh]
ndim = 3

xmin = 0.0
xmax = 18.75

ymin = 0.0
ymax = 18.75

zmin = 0.0
zmax = 18.75

boundary_type_xmin = periodic
boundary_type_xmax = periodic

boundary_type_ymin = periodic
boundary_type_ymax = periodic

boundary_type_zmin = periodic
boundary_type_zmax = periodic

[hydro]
dual_energy     = true
dual_energy_eta = 0.5

gamma0      = 1.666
riemann     = hllc
update      = HydroUpdate_euler_27_passive_scalars

[rad]
update  = RadUpdate_euler_M1
c_rad   = 0.01 speedofLight

absorbing_bc = true

n_groups            = 6
photon_groups_lower = 5.6,11.2,13.6,15.2,24.59,54.42
photon_groups_upper = 11.2,13.6,15.2,24.59,54.42,500.0

uvb_spectrum_file  = /home/astorck/UVB.out
uvb_injection_mode = floor
uvb_boost = 1e0
uvb_sub_ionizing_only = false
uvb_initial_fill   = false
uvb_redshift       = 0.0

[source_terms]
updates = SourceUpdate_UV_Background,CoolingUpdate_PRISM_hydro

[cooling]
reduce_chunk_size   = 8
max_substeps        = 100000
verbose_passes      = false
include_HM12_UVB    = false
UV_background_G0    = 0.0
data_path           = /home/astorck/repos/Dyablo/core/src/source_terms/PRISM/gizmo_rtz/data
ions                = H_I,H_II,H2,He_I,He_II,He_III,C_I,C_II,C_III,C_IV,C_V,C_VI,C_VII,O_I,O_II,O_III,O_IV,O_V,O_VI,O_VII,O_VIII,O_IX

[movie]
enabled             = false
image_resolution    = 512
width               = 2.34375 kpc
time_cadence        = 0.02 Myr
output_variables    = rho,xH_I,xH2,xC_II,xO_I,xO_II,xO_III,e_rad_0,e_rad_1,e_rad_2
projection_axis     = z,y
trigger_on_output   = false
output_first_iter    = false

[output]
outputDir                   = /data100/astorck/G8/sim/UVbackground
outputPrefix                 = G8

write_variables             = rho,rho_vx,rho_vy,rho_vz,e_tot,e_int,e_rad_0,e_rad_1,e_rad_2,e_rad_3,nH,nHe,nCO,nC,nO,xH_I,xH_II,xH2,xHe_I,xHe_II,xHe_III,xC_I,xC_II,xC_III,xC_IV,xC_V,xC_VI,xC_VII,xO_I,xO_II,xO_III,xO_IV,xO_V,xO_VI,xO_VII,xO_VIII,xO_IX,PRISM_iter
write_particle_variables    = stars/vx,stars/vy,stars/vz,stars/birth_time,stars/birth_mass,stars/mass

[units]
length  = 1 kpc
time    = 1 Myr
mass    = 1 solar_mass
