[run]
tEnd        = 1000
nStepmax    = 100000
output_frequency    = 100

initial_conditions = uniform,gadget

n_passive_scalars       = 25
passive_scalars_init    = constant_metallicity
passive_scalars_names   = nH,nHe,nC,nO,xH_I,xH_II,xHe_I,xHe_II,xHe_III,xC_I,xC_II,xC_III,xC_IV,xC_V,xC_VI,xC_VII,xO_I,xO_II,xO_III,xO_IV,xO_V,xO_VI,xO_VII,xO_VIII,xO_IX

[gadget]
inputFile = /data/anatole/G8/ICs/G8_test_supersample.hdf5

[constant_metallicity]
metallicity     = 0.0139e-1
metals          = H,He,C,O
metal_mass      = 1.008,4.0026,12.0107,15.9994

ions        = xH_I,xH_II,xHe_I,xHe_II,xHe_III,xC_I,xC_II,xC_III,xC_IV,xC_V,xC_VI,xC_VII,xO_I,xO_II,xO_III,xO_IV,xO_V,xO_VI,xO_VII,xO_VIII,xO_IX
ion_fracs   = 1,0,1,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0

cie_initialization = true

[InitialConditions_uniform]
fields  = e_rad_0,fx_rad_0,fy_rad_0,fz_rad_0,e_rad_1,fx_rad_1,fy_rad_1,fz_rad_1,e_rad_2,fx_rad_2,fy_rad_2,fz_rad_2,e_rad_3,fx_rad_3,fy_rad_3,fz_rad_3
values = 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

[particles]
update_position             = ParticleUpdate_CIC_move
update_density              = ParticleUpdate_CIC_density
density_projected_arrays    = particles

; source_term = ParticleUpdate_star_formation,ParticleUpdate_feedback,ParticleUpdate_radiative_feedback_BPASS

; [star_formation]
; density_threshold     = 1 proton_mass/cm**3 
; epsilon_star          = 0.10
# if using the alt version of the star formation
; particle_mass         = 5000.0

; [star_feedback]
; bpass_data_path   = /data/anatole/BPASS/
; temp_metallicity  = 0.0139e-1

[dt]
; Compute_dt_rad
dt_kernel       = Compute_dt_particle_velocity,Compute_dt_hydro
hydro_cfl        = 0.8
particle_cfl     = 0.8

[gravity]
solver = GravitySolver_cg
CG_eps = 1e-2
4_Pi_G = 5.65298452e-11

[amr]
level_min = 4
level_max = 4

bx = 8
by = 8
bz = 8

nbOctsPerGroup = 1024

markers_kernel              = RefineCondition_mass
# don't refine anywhere
mass_coarsen                = 1e15
mass_refine                  = 1e16
# refine everywhere to go unigrig 1 level higher
; mass_coarsen                = 1e-16
; mass_refine                  = 1e-15
load_balancing_frequency    = 1000
cycle_frequency             = 10000

[mesh]
ndim = 3

xmin = 0.0
xmax = 18.75

ymin = 0.0
ymax = 18.75

zmin = 0.0
zmax = 18.75

boundary_type_xmin = periodic
boundary_type_xmax = periodic

boundary_type_ymin = periodic
boundary_type_ymax = periodic

boundary_type_zmin = periodic
boundary_type_zmax = periodic

[hydro]
gamma0      = 1.666
riemann     = hllc
update      = HydroUpdate_euler_25_passive_scalars

[rad]
; update  = RadUpdate_euler_M1
c_rad   = 0.001 speedofLight

absorbing_bc = true

n_groups            = 4
photon_groups_lower = 13.6,15.2,24.59,54.42
photon_groups_upper = 15.2,24.59,54.42,500

[source_terms]
updates = CoolingUpdate_PRISM_hydro

[cooling]
data_path   = /home/storckanatole/repos/Dyablo/core/src/source_terms/PRISM/gizmo_rtz/data

relaxing    = true
ions        = H_I,H_II,He_I,He_II,He_III,C_I,C_II,C_III,C_IV,C_V,C_VI,C_VII,O_I,O_II,O_III,O_IV,O_V,O_VI,O_VII,O_VIII,O_IX

[movie]
enabled             = true
output_frequency    = 50
output_variables    = rho,rho_vx,rho_vy,rho_vz,e_tot,e_rad_0,fx_rad_0,fy_rad_0,fz_rad_0,e_rad_1,fx_rad_1,fy_rad_1,fz_rad_1,e_rad_2,fx_rad_2,fy_rad_2,fz_rad_2,e_rad_3,fx_rad_3,fy_rad_3,fz_rad_3,nH,nHe,nC,nO,xH_I,xH_II,xHe_I,xHe_II,xHe_III,xC_I,xC_II,xC_III,xC_IV,xC_V,xC_VI,xC_VII,xO_I,xO_II,xO_III,xO_IV,xO_V,xO_VI,xO_VII,xO_VIII,xO_IX
projection_axis     = z,y
trigger_on_output   = true
output_first_iter    = true

[output]
outputDir                   = /data/anatole/G8/sim/relaxation_cie_test
outputPrefix                 = G8_relaxing

write_variables             = rho,rho_vx,rho_vy,rho_vz,e_tot,e_rad_0,fx_rad_0,fy_rad_0,fz_rad_0,e_rad_1,fx_rad_1,fy_rad_1,fz_rad_1,e_rad_2,fx_rad_2,fy_rad_2,fz_rad_2,e_rad_3,fx_rad_3,fy_rad_3,fz_rad_3,nH,nHe,nC,nO,xH_I,xH_II,xHe_I,xHe_II,xHe_III,xC_I,xC_II,xC_III,xC_IV,xC_V,xC_VI,xC_VII,xO_I,xO_II,xO_III,xO_IV,xO_V,xO_VI,xO_VII,xO_VIII,xO_IX
write_particle_variables    = particles/vx,particles/vy,particles/vz,particles/mass,particles/birth_time

[units]
length  = 1 kpc
time    = 1 Myr
mass    = 1 solar_mass
