[run]
tEnd=0.300
nStepmax=1000000
nOutput=1
initial_conditions=uniform,simple_particles
output_frequency=100

[constant_metallicity]
Z_over_Zsun     = 0.1
metals          = H,He,C,O
metal_mass      = 1.008,4.0026,12.0107,15.9994

ions        = xH_I,xH_II,xH2,xHe_I,xHe_II,xHe_III,xC_I,xC_II,xC_III,xC_IV,xC_V,xC_VI,xC_VII,xO_I,xO_II,xO_III,xO_IV,xO_V,xO_VI,xO_VII,xO_VIII,xO_IX
cie_initialization = true

[InitialConditions_uniform]

fields  = rho,e_tot,rho_vx,rho_vy,rho_vz,e_rad_0,fx_rad_0,fy_rad_0,fz_rad_0,e_rad_1,fx_rad_1,fy_rad_1,fz_rad_1,e_rad_2,fx_rad_2,fy_rad_2,fz_rad_2,e_rad_3,fx_rad_3,fy_rad_3,fz_rad_3,e_rad_4,fx_rad_4,fy_rad_4,fz_rad_4,e_rad_5,fx_rad_5,fy_rad_5,fz_rad_5

# 1000 h/cc, 30 K/mu
values = 1e3,2.5e-1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

# 1e-1 h/cc, 30 K/mu
;values = 1e-1,2.5e-5,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

[passive_scalars]
n_passive_scalars       = 27
passive_scalars_init    = constant_metallicity
passive_scalars_names   = nH,nHe,nCO,nC,nO,xH_I,xH_II,xH2,xHe_I,xHe_II,xHe_III,xC_I,xC_II,xC_III,xC_IV,xC_V,xC_VI,xC_VII,xO_I,xO_II,xO_III,xO_IV,xO_V,xO_VI,xO_VII,xO_VIII,xO_IX

[cooling]
max_substeps        = 100000
rt_smooth           = true
rad_residual_floor   = 1e-3
include_HM12_UVB    = false
UV_background_G0    = 0.0
data_path           = /home/astorck/repos/Dyablo/core/src/source_terms/PRISM/gizmo_rtz/data
ions                = H_I,H_II,H2,He_I,He_II,He_III,C_I,C_II,C_III,C_IV,C_V,C_VI,C_VII,O_I,O_II,O_III,O_IV,O_V,O_VI,O_VII,O_VIII,O_IX


[simple_particles]
attributes = vx,vy,vz,mass,birth_mass,birth_time,metallicity
npart = 1
mass = 1e2
birth_mass = 1e2
px = 0.0025
py = 0.0025
pz = 0.0025
birth_time = 0.0
metallicity = 0.1
vx = 0
vy = 0
vz = 0

[particles]
families    = particles
source_term = ParticleUpdate_radiative_feedback_BPASS

[star_feedback]
star_family     = particles
bpass_data_path = /data100/astorck/BPASS/

[source_terms]
updates = CoolingUpdate_PRISM_GPU_hydro

[dt]
dt_kernel=Compute_dt_rad,Compute_dt_hydro
hydro_cfl=0.8
wait_for_radiation = false

[amr]
level_min=3
level_max=3

bx=8
by=8
bz=8
; bz=3

nbOctsPerGroup=1024

; markers_kernel=RefineCondition_pseudo_gradient
; epsilon_refine=0.1
; epsilon_coarsen=0.05

load_balancing_frequency=10000
cycle_frequency=10000

[mesh]
ndim=3

xmin=0.0
xmax=1.0

ymin=0.0
ymax=1.0

zmin=0.0
zmax=1.0

boundary_type_xmin=reflecting
boundary_type_xmax=absorbing

boundary_type_ymin=reflecting
boundary_type_ymax=absorbing

boundary_type_zmin=reflecting
boundary_type_zmax=absorbing

[hydro]
; dual_energy     = true
; dual_energy_eta = 0.5

gamma0      = 1.666
riemann     = hllc
update      = HydroUpdate_euler_27_passive_scalars

[rad]
update  = RadUpdate_euler_M1
c_rad   = 0.1 speedofLight

absorbing_bc = false

n_groups            = 6
photon_groups_lower = 5.6,11.2,13.6,15.2,24.59,54.42
photon_groups_upper = 11.2,13.6,15.2,24.59,54.42,500.0

uvb_spectrum_file  = /home/astorck/UVB.out
uvb_injection_mode = floor
uvb_boost = 1e0
uvb_sub_ionizing_only = false
uvb_initial_fill   = false
uvb_redshift       = 0.0


[output]
outputDir                   = /data100/astorck/stromgren/1e3hcc_30Kmu_4pc
;outputDir                   = /data100/astorck/stromgren/1e-1hcc_30Kmu
outputPrefix                 = photoheat_test

write_variables             = rho,rho_vx,rho_vy,rho_vz,e_tot,e_int,e_rad_0,e_rad_1,e_rad_2,e_rad_3,e_rad_4,e_rad_5,nH,nHe,nCO,nC,nO,xH_I,xH_II,xH2,xHe_I,xHe_II,xHe_III,xC_I,xC_II,xC_III,xC_IV,xC_V,xC_VI,xC_VII,xO_I,xO_II,xO_III,xO_IV,xO_V,xO_VI,xO_VII,xO_VIII,xO_IX,PRISM_iter
write_particle_variables    = particles/mass

[units]
time    = 1 Myr
length  = 4 pc
density = 1 proton_mass/cm3
