[run]
tEnd=0.100
nStepmax=100000
nOutput=1
initial_conditions=uniform,simple_particles
output_frequency=1

[InitialConditions_uniform]

# For H and He
; fields=rho,e_tot,rho_vx,rho_vy,rho_vz,e_rad,fx_rad,fy_rad,fz_rad,nH,nHe,xH_I,xH_II,xH2,xHe_I,xHe_II,xHe_III
; values=1e0,1e0,0,0,0,0,0,0,0,0.76,0.0599610253335332,1.0,0,0,1.0,0,0

# Adding C and O (no H2 or CO)
; fields=rho,e_tot,rho_vx,rho_vy,rho_vz,e_rad,fx_rad,fy_rad,fz_rad,nH,nHe,nC,nO,xH_I,xH_II,xHe_I,xHe_II,xHe_III,xC_I,xC_II,xC_III,xC_IV,xC_V,xC_VI,xC_VII,xO_I,xO_II,xO_III,xO_IV,xO_V,xO_VI,xO_VII,xO_VIII,xO_IX
; values=1e0,1e0,0,0,0,0,0,0,0,0.7524,0.05936138541878507,0.0004162850720173175,0.0003125195324707794,1.0,0,1.0,0,0,1.0,0,0,0,0,0,0,1.0,0,0,0,0,0,0,0,0

# H and He group RT (6 bands, 5.6 --> 500) (no H2 or CO)
# fields=rho,e_tot,rho_vx,rho_vy,rho_vz,e_rad_0,fx_rad_0,fy_rad_0,fz_rad_0,e_rad_1,fx_rad_1,fy_rad_1,fz_rad_1,e_rad_2,fx_rad_2,fy_rad_2,fz_rad_2,e_rad_3,fx_rad_3,fy_rad_3,fz_rad_3,e_rad_4,fx_rad_4,fy_rad_4,fz_rad_4,e_rad_5,fx_rad_5,fy_rad_5,fz_rad_5,nH,nHe,xH_I,xH_II,xHe_I,xHe_II,xHe_III
# values=1e0,1e0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.76,0.0599610253335332,1.0,0,1.0,0,0

# H and He group RT (2 bands, 5.6 --> 500) (no H2 or CO)
; fields=rho,e_tot,rho_vx,rho_vy,rho_vz,e_rad_0,fx_rad_0,fy_rad_0,fz_rad_0,e_rad_1,fx_rad_1,fy_rad_1,fz_rad_1,nH,nHe,xH_I,xH_II,xHe_I,xHe_II,xHe_III
; values=1e0,1e0,0,0,0,0,0,0,0,0,0,0,0,0.76,0.0599610253335332,1.0,0,1.0,0,0


fields=rho,e_tot,rho_vx,rho_vy,rho_vz,e_rad_0,fx_rad_0,fy_rad_0,fz_rad_0,nH,nHe,xH_I,xH_II,xHe_I,xHe_II,xHe_III
values=1e0,1e0,0,0,0,0,0,0,0,0.76,0.0599610253335332,1.0,0,1.0,0,0

[dt]
dt_kernel=Compute_dt_rad

[simple_particles]
attributes = vx,vy,vz,mass,birth_time
npart = 1
# 4e-4 --> 10 Msun
mass = 4e-4
px = 0.0025
py = 0.0025
pz = 0.0025
birth_time = -0
vx = 0
vy = 0
vz = 0

[particles]
source_term = ParticleUpdate_radiative_feedback

[star_feedback]
; photon_rate = 1e48

# from reflective boundary test
photon_rate = 1.25e47

[source_terms]
updates = CoolingUpdate_PRISM_hydro

[cooling]
data_path=/home/astorck/repos/Dyablo/core/src/source_terms/PRISM/gizmo_rtz/data

# For H and He
ions=H_I,H_II,He_I,He_II,He_III

# Adding C and O (no H2 or CO)
; ions=H_I,H_II,He_I,He_II,He_III,C_I,C_II,C_III,C_IV,C_V,C_VI,C_VII,O_I,O_II,O_III,O_IV,O_V,O_VI,O_VII,O_VIII,O_IX

[amr]
level_min=1
level_max=1

bx=32
by=32
bz=4
; bz=3

nbOctsPerGroup=2048
loadbalance_coherent_levels=2

markers_kernel=RefineCondition_pseudo_gradient
epsilon_refine=0.1
epsilon_coarsen=0.05

load_balancing_frequency=1000
cycle_frequency=1000

[mesh]
ndim=3

xmin=0.0
xmax=1.0

ymin=0.0
ymax=1.0

; zmin=0.0
; zmax=1.0
zmin=0.0
zmax=0.2

boundary_type_xmin=reflecting
boundary_type_xmax=absorbing

boundary_type_ymin=reflecting
boundary_type_ymax=absorbing

boundary_type_zmin=reflecting
boundary_type_zmax=absorbing

[hydro]
gamma0=1.666
riemann=hllc

[rad]
update=RadUpdate_euler_M1
c_rad=0.01 speedofLight

; n_groups=2
; photon_groups_lower=5.6,13.6
; photon_groups_upper=11.2,13.61

n_groups=1
photon_groups_lower=13.6
photon_groups_upper=13.61


[output]
outputDir=/data100/astorck/dyablo_testing/.

# For H and He
; outputPrefix=test_PRISM_HandHe_1e48Nphot_thinRTband_onlyHI_noUVB_T1e4blackbodyXsection
; write_variables=rho,rho_vx,rho_vy,rho_vz,e_tot,e_rad,fx_rad,fy_rad,fz_rad,nH,nHe,xH_I,xH_II,xHe_I,xHe_II,xHe_III

# Adding C and O (no H2 or CO)
; outputPrefix=test_PRISM_CandO
; write_variables=rho,rho_vx,rho_vy,rho_vz,e_tot,e_rad_0,fx_rad_0,fy_rad_0,fz_rad_0,nH,nHe,nC,nO,xH_I,xH_II,xHe_I,xHe_II,xHe_III,xC_I,xC_II,xC_III,xC_IV,xC_V,xC_VI,xC_VII,xO_I,xO_II,xO_III,xO_IV,xO_V,xO_VI,xO_VII,xO_VIII,xO_IX

# For H and He with group RT (no H2 or CO)
; outputPrefix=test_PRISM_HandHe_01c
; write_variables=rho,rho_vx,rho_vy,rho_vz,e_tot,e_rad_0,fx_rad_0,fy_rad_0,fz_rad_0,e_rad_1,fx_rad_1,fy_rad_1,fz_rad_1,nH,nHe,xH_I,xH_II,xHe_I,xHe_II,xHe_III

outputPrefix=test_PRISM_H_0001c_cornered_thin_testCloseness_derefined
write_variables=rho,rho_vx,rho_vy,rho_vz,e_tot,e_rad_0,fx_rad_0,fy_rad_0,fz_rad_0,nH,nHe,xH_I,xH_II,xHe_I,xHe_II,xHe_III

[units]
time = 1 Myr
length = 40 pc
density = 1 proton_mass/cm3
